version: '3.8'

services:

  rec_book_bot_database:
    container_name: rec_book_bot_database
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  api-server:
    container_name: api-server
    build: ./api-server
    env_file:
      - .env
    depends_on:
      - rec_book_bot_database
    volumes:
      - ./api-server/:/app
      - /api-server/node_modules
    ports:
      - ${API_PORT_OUTSIDE}:3000

  bot-server:
    container_name: bot-server
    build: ./bot-server
    env_file:
      - .env
    depends_on:
      - rec_book_bot_database
      - api-server
    volumes:
      - ./bot-server/:/app
      - /bot-server/node_modules