migration-generate:
	docker exec -i api-server npm run migration:generate
migration-run:
	docker exec -i api server npm run migration:run
migration-revert:
	docker exec -i api server npm run migration:revert